### PR TITLE
this change allows the change of the memberOf attribute

### PR DESCRIPTION
**Pull request by ritchieGitHub**
Some organisations have other attributes than memberOf that specifies the groups.
With this pull request it is changeable.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Thanks for catching the issue. 
Do you really need a setter method? If no, I would just fix the jelly file.

**Comment by oleg-nenashev** [comment]
Somebody also should create an issue in JIRA

**Comment by ritchieGitHub** [comment]
Without the setter the script failed in my system, if the current version can do without then it is not nessesary anymore.

**Comment by oleg-nenashev** [comment]
@ritchieGitHub 
The constructor is correct, so it should work. I'll try to check it on this week.

**Comment by oleg-nenashev** [comment]
I confirm the code works for me without a setter. I can just pick https://github.com/entis-group/ldap-plugin/commit/1b87f243a70e356b40b0c3f52a039acbb9d48b61 to the master branch

**Comment by ritchieGitHub** [comment]
thanks!

**Comment by KostyaSha** [comment]
right, should be `attributeName` in tact with constructor

**Comment by JesperTerkelsen** [comment]
Bump - just ran into this
Why was this never merged ?

**Comment by rdpa** [comment]
Bump again. This is giving us trouble right now.

**Comment by andresrc** [comment]
Included in https://github.com/jenkinsci/ldap-plugin/pull/10

**Pull request closed without merging**
