### PR TITLE
[JENKINS-55813] Add support for LDAP password policy attributes (account locking)

### PR DESCRIPTION
**Pull request by jvz**
Builds on top of #49, ~so diff against Jesse's branch for an easier view: https://github.com/jglick/ldap-plugin/compare/spring-5303-new...jvz:JENKINS-55813-spring-security~

https://issues.jenkins.io/browse/JENKINS-55813

### CODE REVIEW

**Review by rsandell — APPROVED** [review]

**Comment by jglick** [comment]
Needs `master` merged in to be reviewable. I am not sure I am a competent reviewer for this; perhaps better left to CERT team.

**Comment by rsandell** [comment]
@jvz can you merge with current master branch please. I'd like to see that it builds cleanly before I attempt to merge :)

**Comment by jvz** [comment]
Can do. I'll also be trying this plugin out in Active Directory to ensure the attribute checks here match the ones in the AD plugin updates.

**Comment by jvz** [comment]
Merged back with master, and I tested this out with Active Directory as well.

**Pull request merged**
