### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by jglick**
#49 plus assorted code cleanups.

### CODE REVIEW

**Comment by jglick** [comment]
Windows test failure looks like a flake.

**Review by rsandell — APPROVED** [review]

**Comment by rsandell** [comment]
Rebuild successful.

**Comment by jglick** [comment]
Thanks. Do you have a ci.jenkins.io login or can you now rebuild from **Checks**?

**Comment by rsandell** [comment]
I first tried to rebuild from Checks, but it didn't respond, so I (ab)used my ci.jenkins.io login :)

**Comment by rsandell** [comment]
@jglick this is also ready for merge I guess?

**Comment by jglick** [comment]
> this is also ready for merge I guess?

Yes. You may prefer to release #49 first and merge this later. I have no particular opinion.

**Comment by rsandell** [comment]
I'd like to get this released with #49 as 2.0 and then release #59  as 2.1

**Pull request merged**
