### PR TITLE
Use encoding of the request

### PR DESCRIPTION
**Pull request by offa**
_See #170 discussion._

/cc @basil 

------------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — APPROVED** [review]
Definitely a more logical choice than the JVM character encoding, which is completely unrelated to the encoding of the HTTP request. Would be great if you could set a breakpoint and verify that it is always UTF-8 in practice, since that is what we expect. (And if it isn't, then we clearly haven't understood the problem!) But that is optional since I think the risk of regression is low.

**Comment by offa** [comment]
There's just one corner case: `getCharacterEncoding()` could theoretically return `null` in case the request hasn't specified an encoding. This would end in `IOUtils.toString()` using default encoding (again). Should we use UTF-8 as a fallback here instead?

> Would be great if you could set a breakpoint and verify that it is always UTF-8 in practice, since that is what we expect.

All right, I'll do some testing.

**Comment by basil** [comment]
> Should we use UTF-8 as a fallback here instead?

I think that makes sense. Certainly it seems like a better fallback than the JVM's default encoding, which as I mentioned earlier is completely unrelated.

**Comment by offa** [comment]
As expected the request was UTF-8 in my tests.

However, I have only Linux hosted systems around which use UTF-8 by default (`file.encoding`).

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Review by jtnord — APPROVED** [review]

**Review by car-roll — APPROVED** [review]

**Pull request merged**
